### ISSUE TITLE
LC-MS workflow for metabolomics data dependent analysis

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaMS#12]
Establish LC-MS workflow for metabolomics data dependent analysis:

- [X] Development of targeted data processing script
- [ ] Implementation of CoreMS objs (50%) 
- [ ] WDL and metadata products

**Comment by ssarrafan** [comment]
@corilo based on the PNNL team meeting yesterday I assume I should move this issue to the October sprint.  Can you please confirm?

**Comment by corilo** [comment]
Yes, please move it to the October sprint. Thanks!

Em qua., 29 de set. de 2021 às 16:51, ssarrafan ***@***.***>
escreveu:

**Comment by ssarrafan** [comment]
Hi @corilo 
Would you like this closed, or moved to another sprint?

**Comment by corilo** [comment]
Hi Setareh,

Please move it to november

I'll add details on the progress and create bullet points on it.

Basically the core algorithm is done, I'm halfway done with the data
structure, then after that I need to add the CLI and WDL and connect the
molecular reference database.

**Comment by corilo** [comment]
- [X] Development of targeted data processing script
- [ ] Implementation of CoreMS objs
- [ ] WDL and metadata products

**Comment by ssarrafan** [comment]
Moving this to December sprint to finish the additional tasks outlined per @corilo via Slack

**Comment by ssarrafan** [comment]
Hi @corilo.  Do you anticipate this issue can be closed by Thursday?  Or does it need to be continued it to January?

**Comment by corilo** [comment]
It won't be done by Thursday, please move it to January.

Thanks!!!

Em ter., 14 de dez. de 2021 às 10:55, ssarrafan ***@***.***>
escreveu:

**Comment by ssarrafan** [comment]
Adding to the February sprint per @corilo

**Comment by ssarrafan** [comment]
@corilo it's mid-sprint so I wanted to check to see if you had any blockers or needed any help with this issue.  Please let me know if I can help with anything.  Thanks!

**Comment by ssarrafan** [comment]
@corilo are you still working on this issue?  should it be moved to the March sprint?

**Comment by ssarrafan** [comment]
I'll move this to March but let me know if you're not working on it during March. @corilo

**Comment by ssarrafan** [comment]
@corilo do you have any updates on this issue?  I am trying to close out the sprint on time since I'll be off next week.  Thanks for your help.
