### ISSUE TITLE
Design and enable metadata generation for lipidomics workflow

### ISSUE THREAD

**Issue by kheal** [microbiomedata/metaMS#29]
What is left: 

- [x] https://github.com/microbiomedata/issues/issues/805

**Comment by kheal** [comment]
These metadata changes will be in alignment with the Berkeley schema

**Comment by brynnz22** [comment]
editing to create smaller subtasks of what is left to do. Most of the lipidomics has been designed and written, what is left to do is:

- [ ] [Add functionality for processed data to lipidomics metadata gen script](https://github.com/microbiomedata/issues/issues/752)
- [ ] Add functionality for `MaterialProcessing` functionality to lipidomics metadata gen script
- [ ] Add documentation to lipidomics metadata gen script
- [ ] Add optional parameter functionality if biosamples already exist or will need to be created for lipidomics metadata gen script.

Can create issues for these as needed.

**Comment by mslarae13** [comment]
@brynnz22 can we move this meta-issue into in progress if it has sub-issues that you'll be adding and are still in progress? Or is there a task for this that is in review or ready to close?

**Comment by brynnz22** [comment]
Its done, its just in review with requested changes.

**Comment by mslarae13** [comment]
Hi @brynnz22 , Still in review?

**Comment by brynnz22** [comment]
Yep! I will have it done by the retreat.
