### ISSUE TITLE
Add private attributes and associated properties to LCMSMassFeatures class to lcms_dev on CoreMS

### ISSUE THREAD

**Issue by kheal** [microbiomedata/metaMS#46]
This is next in line for mergining into lcm_dev after #38 .

**Comment by kheal** [comment]
This MR is ready in gitlab: https://code.emsl.pnl.gov/mass-spectrometry/corems/-/merge_requests/91

**Comment by ssarrafan** [comment]
@kheal let me know if I can help nudge anyone to review the MR.

**Comment by kheal** [comment]
Thanks @ssarrafan - I think @corilo has it on his radar.
