### ISSUE TITLE
Metabolomics workflow distribution outside PNNL

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaMS#5]
Metabolomics workflow is working at PNNL but need to figure out DB infrastructure that would allow it to be distributed outside of PNNL.

**Comment by corilo** [comment]
@ssarrafan, @kfagnan closing the issue based on today discussion during Tech Sync Meeting, we are working on the long term solution for the issue, and we agreed it should not be the priority for May sprint
