### ISSUE TITLE
Issue with running MetaMS and minwidl

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/metaMS#7]
For metaMS:

After following standard install procedure, when I run:

`metaMS dump_json_template MetamsFile.json`

**Error**:

```
Traceback (most recent call last):
  File "/home/mbabinski/miniconda3/bin/metaMS", line 5, in <module>
    from metaMS.cli import cli
ModuleNotFoundError: No module named 'metaMS'
```

For miniwdl:

After following installation, when I run:

`miniwdl run wdl/metaMS.wdl -i wdl/metams_input.json --verbose --no-cache --copy-input-files:`

**Error**: 

`task runMetaMS (wdl/metaMS.wdl Ln 5 Col 1) failed :: dir: "/panfs/biopan04/scratch-mbabinski/metaMS/20210624_134633_gcmsMetabolomics/call-runMetaMS", error: "DockerException", message: "Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))"`

With docker image there was no issue. 

Thanks!
Michal

**Comment by corilo** [comment]
@Michal-Babins 

for the min-wdl error:
 error: "**DockerException**", message: "Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))

looks like you are having issues pulling the docker image from the registry, make sure you are logged on docker registry

for the metaMS cli error, 

I confirmed that PyPi package release is not working, but the installation from source works.  The recommendation is to install it from source, clone codebase and install (pip3 install --editable .),  until a solution for the PyPi package is found. 

Regards, 

Yuri

**Comment by corilo** [comment]
PyPi package has been fixed, setup code has been update and and a new version uploaded of the package release on PyPi (2.1.3),

**Comment by Michal-Babins** [comment]
Command works when installing from source. But looks like I am getting back an issue with sql database:

With:

`metaMS run-gcms-workflow /panfs/biopan04/scratch-mbabinski/metaMS/data/MetamsFile.json `

**Error**:
`sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file`

**Comment by corilo** [comment]
Yes, that is expected, the database is not yet provided.
