### ISSUE TITLE
Preparation Metadata: Metabolomics

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/metaMS#8]
- [ ] #18
- [x] #19
- [ ] #20
- [x] #21
- [x] #22

**Comment by ssarrafan** [comment]
Moving to Oct sprint per Slack message from Montana

**Comment by ssarrafan** [comment]
Moving to the November sprint per Slack message from Montana

**Comment by ssarrafan** [comment]
Adding backlog label and removing from sprints per slack message from @mslarae13 

FYI @SamuelPurvine

**Comment by ssarrafan** [comment]
I checked in with @yuricorilo and @mslarae13 and moving this to August sprint. I also created sub-issues from the list of tasks. @mslarae13 I'll assign this issue but not the sub-tasks until I hear from you for future sprints.

**Comment by ssarrafan** [comment]
Checked in with @turbomam and removing this from the sprint and adding the backlog label.  @mslarae13 let me know if you're planning to work on this the rest of this month.

**Comment by ssarrafan** [comment]
@mslarae13 @anastasiyaprymolenna should this issue remain in the backlog?  Or can I close it?

**Comment by mslarae13** [comment]
I think we can close it in favor of the refactoring work & issues
